# Generated by Django 5.2.10 on 2026-02-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('nic', models.CharField(max_length=12, unique=True)),
                ('role', models.CharField(choices=[('mechanic', 'Mechanic'), ('electrician', 'Electrician'), ('painter', 'Painter'), ('supervisor', 'Supervisor')], max_length=20)),
                ('department', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
