# Generated by Django 5.2.10 on 2026-02-15 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('vin', models.CharField(max_length=50, unique=True, verbose_name='VIN')),
                ('number_plate', models.CharField(max_length=20, unique=True)),
                ('color', models.CharField(max_length=20)),
                ('driving_type', models.CharField(max_length=20)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('fuel_type', models.CharField(max_length=20)),
                ('current_mileage', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
